model_list:
  - model_name: gpt-4o
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0
      aws_region_name: us-east-1                                                                                                                                                                           
      #fallbacks:                                                                                                                                                                                                                                  
      #  - model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0                                                                                                                                                                                
      #  - model: bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0   
  - model_name: text-embedding-3-large
    litellm_params:
      model: bedrock/amazon.nova-2-multimodal-embeddings-v1:0
      aws_region_name: us-east-1   

litellm_settings:
  log_raw_request_response: True
  set_verbose: true
  drop_params: true
  modify_params: true 
  cache: false 
  allowed_origins: ["*"]

general_settings:
  completion_model: gpt-4o