use_default_settings: true

general:
  instance_name: 'searxng-aws'

search:
  autocomplete: 'google'
  formats:
    - html
    - json

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b'
  bind_address: '0.0.0.0'
  port: 8080

engines:
  - name: wolframalpha
    disabled: false    
  - name: wikidata
    disabled: true